apiVersion: v1
kind: Service
metadata:
  name: callerservice
  labels:
    app: callerservice
spec:
  ports:
  - port: 8090
    name: http
  selector:
    app: callerservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: callerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: callerservice
        version: v1
    spec:
      containers:
      - name: callerservice
        image: gcr.io/ibesx-esa-sandbox-00f7f67a/bns/caller-service:5.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: callerservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: callerservice
spec:
  hosts:
  - "*"
  gateways:
  - callerservice-gateway
  http:
  - match:
    - uri:
        exact: /caller/check
    - uri:
        exact: /caller/ping
    - uri:
        exact: /caller/pingvirtual
    - uri:
        exact: /caller/pingip    
    route:
    - destination:
        host: callerservice
        port:
          number: 8090
---        
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: callerservice
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: apigee-rule-callerservice
  namespace: istio-system
spec:
  match: context.reporter.kind == "inbound" && destination.service == "callerservice.default.svc.cluster.local" 
  actions:
  - handler: apigee-handler.apigee.istio-system
    instances:
    - apigee.authorization
    - apigee.analytics
