apiVersion: v1
kind: Service
metadata:
  name: called-service
  labels:
    app: called-service
spec:
  ports:
  - port: 8091
    name: http
  selector:
    app: called-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: called-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: called-service
        version: v1
    spec:
      containers:
      - name: called-service
        image: gcr.io/ibesx-esa-sandbox-00f7f67a/bns/called-service:1.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
      - args:
        - --controlPlaneAuthPolicy
        - MUTUAL_TLS
---
